-- tabel direktori hpg
create table public.direktori_hpg (
  id bigint generated by default as identity primary key,

  kategori_gangguan text CHECK (kategori_gangguan IN ('hama', 'penyakit', 'gulma')),
  nama_jenis text,
  nama_ilmiah text,
  deskripsi text null,
  cara_pengendalian text,
  image_url text null,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Aktifkan RLS (Row Level Security)
alter table public.direktori_hpg enable row level security;

-- Policy: Semua user boleh SELECT (read-only akses)
create policy "Public read access to direktori_hpg"
on public.direktori_hpg
for select
using (true);

create index idx_direktori_hpg_kategori
on public.direktori_hpg (kategori_gangguan);

create index idx_direktori_hpg_nama_jenis
on public.direktori_hpg (nama_jenis);