-- tabel modul edukasi
create table public.modul_edukasi (
  id bigint generated by default as identity primary key,

  kategori text, -- 'Materi', 'Panduan', 'Poster', 'Video'
  sumber text,
  title text,
  subtitle text null,
  image text null,
  file_url text null,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Aktifkan RLS (Row Level Security)
alter table public.modul_edukasi enable row level security;

-- Policy: Semua user boleh SELECT (read-only akses)
create policy "Public read access to modul_edukasi"
on public.modul_edukasi
for select
using (true);

create index idx_modul_edukasi_kategori
on public.modul_edukasi (kategori);

create index idx_modul_edukasi_title
on public.modul_edukasi (title);