-- Tabel untuk menyimpan riwayat analisis bulanan per demoplot
CREATE TABLE public.analisis_kesehatan_lahan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demoplot_id uuid REFERENCES public.demoplot(id) ON DELETE CASCADE,
  
  periode_analisis DATE NOT NULL, -- Bulan/Tahun audit, misal: '2026-05-01'
  skor_kesehatan INTEGER CHECK (skor_kesehatan BETWEEN 0 AND 100),
  
  -- Rata-rata indeks numerik
  avg_ndvi NUMERIC(4,3), -- rentang -1.000 s/d 1.000 (biasanya 0.1 s/d 0.8)
  avg_ndwi NUMERIC(4,3),
  
  -- Persentase klasifikasi area kebun
  pct_sehat NUMERIC(5,2),   -- persen area sehat
  pct_normal NUMERIC(5,2),  -- persen area sedang
  pct_stres NUMERIC(5,2),   -- persen area stres
  pct_terbuka NUMERIC(5,2), -- persen area tanah kosong
  
  -- Data untuk overlay peta resolusi tinggi
  raster_overlay_url TEXT NULL, -- URL gambar heatmap NDVI transparansi 
  anomali_koordinat JSONB NULL,  -- Titik-titik hotspot bermasalah
  
  sumber_citra VARCHAR(50) DEFAULT 'Sentinel-2',
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indeks performa query
CREATE INDEX idx_analisis_kesehatan_demoplot ON public.analisis_kesehatan_lahan(demoplot_id);
CREATE INDEX idx_analisis_kesehatan_periode ON public.analisis_kesehatan_lahan(periode_analisis);

-- Setup RLS (Row Level Security)
ALTER TABLE public.analisis_kesehatan_lahan ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow authenticated read access for analisis kesehatan" 
  ON public.analisis_kesehatan_lahan 
  FOR SELECT 
  TO authenticated 
  USING (true);

-- Allow insert/update for service role (backend API)
CREATE POLICY "Allow service role full access" 
  ON public.analisis_kesehatan_lahan 
  FOR ALL 
  USING (auth.role() = 'service_role');
